## Домашнее задание к 5 уроку

In [7]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

In [8]:
A = np.array([[1,2,0],[0,0,5],[3,-4,2],[1,6,5],[0,1,0]])
A

array([[ 1,  2,  0],
       [ 0,  0,  5],
       [ 3, -4,  2],
       [ 1,  6,  5],
       [ 0,  1,  0]])

In [9]:
U, s, W = np.linalg.svd(A)
V = W.T
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

In [26]:
s

array([8.82, 6.14, 2.53])

In [10]:
U

array([[ 0.17,  0.16, -0.53, -0.8 , -0.16],
       [ 0.39, -0.53,  0.61, -0.43,  0.03],
       [-0.14, -0.82, -0.52,  0.14,  0.07],
       [ 0.89,  0.06, -0.25,  0.38, -0.06],
       [ 0.08,  0.11, -0.08, -0.11,  0.98]])

In [11]:
D

array([[8.82, 0.  , 0.  ],
       [0.  , 6.14, 0.  ],
       [0.  , 0.  , 2.53],
       [0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  ]])

In [12]:
V

array([[ 0.07, -0.37, -0.93],
       [ 0.72,  0.67, -0.21],
       [ 0.69, -0.65,  0.31]])

In [14]:
np.dot(np.dot(U, D), W)

array([[ 1.,  2.,  0.],
       [ 0., -0.,  5.],
       [ 3., -4.,  2.],
       [ 1.,  6.,  5.],
       [-0.,  1., -0.]])

In [18]:
print(f'Евклидова норма матрицы A: {np.linalg.norm(A, 2)}')
print(f'Евклидова норма матрицы D: {np.linalg.norm(D, 2)}')

Евклидова норма матрицы A: 8.824868854820444
Евклидова норма матрицы D: 8.824868854820444


In [19]:
print(f'Норма Фробениуса матрицы A: {np.linalg.norm(A)}')
print(f'Норма Фробениуса матрицы D: {np.linalg.norm(D)}')

Норма Фробениуса матрицы A: 11.045361017187261
Норма Фробениуса матрицы D: 11.045361017187263


In [31]:
print(np.sqrt(np.sum(list(map(lambda x:x*x, s)))))

11.045361017187263
